#!/bin/bash
#mmartin.,3/1/23,Purpose: Calculate days/weeks between two dates.
# 

red='\e[1;31m%s\e[0m\n'                                                                                                                                                      
green='\e[1;32m%s\e[0m\n'
yellow='\e[1;33m%s\e[0m\n'

clear
echo
echo
printf $yellow '    ENTER DATES IN FOLLOWING FORMAT: yyyy/mm/dd'
printf $yellow '    -------------------------------------------'
echo
echo "Enter start date....." 
read STARTDATE
echo "Enter end date....." 
read ENDDATE


diff=$(( ($(date -d "$ENDDATE" +%s) - $(date -d "$STARTDATE" +%s)) ))

days=$(($diff/(60*60*24)))

weeks=$(($days/7))

years=$(($days/365))

echo
printf $green "Days between the two dates are $days"
printf $green  "Weeks between the two dates are $weeks"
echo "(Oops..That's" "$years" "years!"")"













   
