#!/bin/bash
#mmartin.,29/01/23,    Purpose:Print a random joke

################################################################################################
#place 'jokes.txt' into the directory shown below, or change script to show preffered location.
#################################################################################################

awk '
BEGIN{ srand() } 
rand() * NR < 1 { 
    line = $0 
} 
END { print line }' ~/Documents/VariousTexts/jokes.txt







exit


   
