#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'maybe==0.2.1','console_scripts','maybe'
__requires__ = 'maybe==0.2.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('maybe==0.2.1', 'console_scripts', 'maybe')()
    )
