#!/bin/bash
#mmartin.,27/08/21,Purpose: update and upgrade 


RED=$(tput setaf 1 && tput bold)
GREEN=$(tput setaf 2 && tput bold)
YELLOW=$(tput setaf 3 && tput bold)
BLUE=$(tput setaf 4 && tput bold)
STAND=$(tput sgr0)


echo
echo
printf "$GREEN""Update you-get?   ...[y/n]""$STAND"
read x
if [ "$x" = "y" ]
then
echo
printf "$BLUE""Getting Updates (incl you-get).""$STAND"
echo
pip3 install --upgrade you-get;

echo
sudo nala update

fi

if [ "$x" = "n" ]
then
printf "$YELLOW""Getting Updates.""$STAND"

echo
sudo nala update

fi

echo
printf "$RED""Upgrade?   ...[y/n]""$STAND"
read t
if [ "$t" = "y" ]
then 
sudo nala upgrade
fi

echo
if [ "$t" = "n" ]
then 
printf "$GREEN""OK..Closing.""$STAND"
echo
fi

exit


